### ISSUE TITLE
bazel build branch r1.10 on windows ERROR _api_implementation.so

### ISSUE THREAD

**Issue by whb0219** [guihigashi/tf-windows-wheel#1]
ERROR: C:/users/thinkpad/_bazel_thinkpad/26orbg4z/external/protobuf_archive/BUILD:645:1: C++ compilation of rule '@protobuf_archive//:python/google/protobuf/internal/_api_implementation.so' failed (Exit 1): cl.exe failed: error executing command
C:\users\thinkpad_bazel_thinkpad\26orbg4z\execroot\org_tensorflow\external\protobuf_archive\python\google\protobuf\internal\api_implementation.cc : fatal error C1083: 无法打开编译器生成的文件: “”: Invalid argument
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 22363.015s, Critical Path: 4574.16s
INFO: 6185 processes: 6185 local.
FAILED: Build did NOT complete successfully
How to solve compilation errors?
Thank you

**Comment by guihigashi** [comment]
check this link for the error code https://msdn.microsoft.com/en-us/library/et4zwx34.aspx

Anyway, for `1.11.0` I used these commands in `cmd.exe`
```
git checkout v1.11.0
git cherry-pick 77e2686a

call "%ProgramFiles(x86)%\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
call "C:\Users\guihi\Miniconda3\Scripts\activate.bat" py36
set BAZEL_SH=C:\Program Files\Git\usr\bin\bash.exe
set BAZEL_VC=C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
python configure.py
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
bazel-bin\tensorflow\tools\pip_package\build_pip_package tmp --gpu
```
